### ISSUE TITLE
Raise peerDependency for ESLint

### ISSUE THREAD

**Issue by Ryuno-Ki** [lob/eslint-plugin-lob#8]
Hi, Robin,

I want to try out your plugin, but you pinned [ESLint 1.x as peerDependency](https://github.com/lob/eslint-plugin-lob/blob/ca2ab298fd3c43329964299cd4b69de50699df5d/package.json#L34).

According to the [ESLint homepage](http://eslint.org/) ESLint 4.0 is coming.

Are there reasons why I wouldn't be able to use this plugin with a newer version?

**Comment by robinjoseph08** [comment]
Hey @Ryuno-Ki,

There isn't necessarily a reason to prevent it, it's more to make sure that it still works the same way across the different versions. While the plugin API itself didn't really change, the testing configuration did. So it's non-trivial to just update up and ensure that the tests still pass.

It also causes some problems because our [config](https://github.com/lob/eslint-config-lob) is still on v1.x too so we can't update the version of eslint in this repo and still have the config work. So we need to allow the right version/update things in the right order.

This is definitely something we want to do though. We could at least temporarily just allow for all versions above v0.8.0 so it can be used, and then we actually test against the newer versions whenever we have the time. I think that could work.

**Comment by Ryuno-Ki** [comment]
Maybe you could push that as a new major release alpha version to npm registry?

I'm sure, people will report when something breaks :-)

**Comment by robinjoseph08** [comment]
I felt pretty confident that it should work just fine so I released it as v1.1.0. I'll be going back soon and refactoring the tests with the newer version of eslint, but feel free to use it and let us know if there are any problems!
